mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL_TEST)%'
            public_url: '%env(MERCURE_PUBLIC_URL_TEST)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET_KEY)%'
                publish: '*'
